# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
# See https://pre-commit.com/all-hooks.json for hooks details
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
      # https://github.com/pre-commit/pre-commit-hooks#trailing-whitespace
      - id: trailing-whitespace
      # https://github.com/pre-commit/pre-commit-hooks#end-of-file-fixer
      - id: end-of-file-fixer
      # https://github.com/pre-commit/pre-commit-hooks#check-yaml
      - id: check-yaml
        args: [--allow-multiple-documents]
      # https://github.com/pre-commit/pre-commit-hooks#hooks-available
      - id: check-added-large-files
  - repo: https://github.com/alessandrojcm/commitlint-pre-commit-hook
    rev: v9.3.0
    hooks:
        - id: commitlint
          stages: [commit-msg]
          additional_dependencies: ['@commitlint/config-conventional']
  - repo: local
    hooks:
      - id: gomod
        name: gomod
        entry: make mod
        language: system
      - id: gofmt
        name: gofmt
        entry: make fmt
        language: system
      - id: goimports
        name: goimports
        entry: make imports
        language: system
      - id: test
        name: test
        entry: make test
        language: system
