FROM golang:1.13.1-alpine as builder
ENV GO111MODULE=on
ENV GOPROXY=https://goproxy.cn,direct
ENV GOSUMDB=off
RUN mkdir /build
ADD . /build/
WORKDIR /build
RUN go build -o main main.go
RUN go get github.com/CatchZeng/jenkinsapi

FROM alpine:3.7

# https://pkgs.alpinelinux.org/packages
RUN apk add  --no-cache --repository http://dl-cdn.alpinelinux.org/alpine/v3.7/main/ git=2.15.4-r0
RUN apk add  --no-cache --repository http://dl-cdn.alpinelinux.org/alpine/v3.7/main/ bash=4.4.19-r1
RUN apk add  --no-cache --repository http://dl-cdn.alpinelinux.org/alpine/v3.7/main/ openssh=7.5_p1-r10

RUN mkdir /app
COPY --from=builder /build/main /app
COPY --from=builder /go/bin/jenkinsapi /usr/bin/jenkinsapi
WORKDIR /app
EXPOSE 8888
CMD ["./main"]